version: '2.1'

services:
  app:
    build: .
    environment:
      DATABASE_NAME: coffee
 
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: coffee
    depends_on:
      
      db:
        condition: service_healthy
  
  db:
    image: healthcheck/mysql:latest
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: coffee