version: '2.1'

services:
  app:
    build: .
    environment:
      DATABASE_NAME: coffee
 
    ports:
      - 3000:8080
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: healthcheck/mysql:latest
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: root
      MYSQL_DATABASE: coffee